MobileNativeFoundation/index-import

- README.md
The link to `IndexUnitWriter` is mistakenly to the `.cpp` file, but it was intended to be the header. This fixes that.
> Link to IndexUnitWriter.h, not .cpp

- index-import.cpp
This `{}` pair is unnecessary, and using the `llvm` format style caused two closing `}` at the same indentation level, which is weird.
> Remove unnecessary {} around case body

- .clang-format
The initial `.clang-format` was produced by a `clang-format` built from git, not from an official release. This `.clang-format` did not work with the latest current release (v8.0.0). This removes those incompatible settings.
> Fix .clang-format to support v8

- index-import.cpp
* Fix a bug where if record subdirectories already existed, it would
print an error. fs::create_subdirectories() correctly creates all
intermediate subdirectories and saves the need to check for
existence.
* Fix a problem where if the regex passed in the command line didn't
compile, it would crash. Now it properly reports an error.
> Fix a few bugs

- index-import.cpp
Add `cloneRecord`, which makes use of APFS cloning. Additionally, the no-op record copying optimization is embedded within `cloneRecord`.
LLVM's `fs::copy_file` supports file cloning, but that support isn't in the swift-5.0.x branches. When upgrading to swift-5.1, this could use `fs::copy_file` again.
> Use APFS cloning (actually)

- tests/run.sh
This would have caught the bug introduced by #15 and fixed by #20.
> Clean test output before each run

- CMakeLists.txt
The `target_link_options` function was added in v3.13.
See: https://cmake.org/cmake/help/v3.13/command/target_link_options.html
> Specific correct min CMake version

- tests/multiple/expected.txt
This is a change to support #24, which improves performance by processing indexes concurrently.
Using the [`CHECK-DAG` directive](https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-dag-directive) ensures the tests still pass, even if the output is interleaved because of concurrency. This change makes the tests pass when run with #24.
> Change tests to support parallel processing

- CMakeLists.txt
Adds a conditional call to `project()`. In a recent version of CMake, it started to produce the below warning.
```
CMake Warning (dev) in CMakeLists.txt:
No project() command is present.  The top-level CMakeLists.txt file must
contain a literal, direct call to the project() command.  Add a line of
code such as
project(ProjectName)
near the top of the file, but after cmake_minimum_required().
CMake is pretending there is a "project(Project)" command on the first
line.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> CMake: Add project(index-import)

- README.md
The original location is a bit misleading for a new comer like me. After I clicked the link, I tried to follow the instruction by running "swift/utils/build-script --release-debuginfo", and it failed due to missing ninja.
Then I scrolled up, and learned that I should "brew install ninja". Unfortunately, that wasn't enough either, because I also needed to to `./swift/utils/update-checkout --clone` first.
I think using the "System Requirements" as the entry point would probably be a better starting place for someone new to Swift source code.
> Use the link of "System Requirements" for Swift

- index-import.cpp
Follow up to #24.
Parallel importing resulted in verbose output being printed in non-deterministic order. This is a problem for both human consumption of verbose output, and for the tests which use the verbose output.
This fix is to use a unique buffer for each call to `remapIndex()`, in which the verbose output is collected. After function completion, the output is printed to stdout. Printing is done under lock. In theory there shouldn't be much overhead or contention to the lock. The lock is only used when verbose mode is enabled, and verbose mode will generally only be enabled when running tests, or, during development, and both cases aren't performance sensitive. For normal use, verbose will be off and so no locking will occur.
> Buffer verbose output, and flush under lock

- index-import.cpp
Apply the remappings to the source/target paths for each `#include` as well. This is relevant to C/C++/ObjC sources and not Swift.
The goal of this change was to allow Xcode to correctly resolve `#include` statements from a remapped index that originated from Bazel. This change doesn't fully fix that but is part of the solution.
> Remap source/target paths for includes

- index-import.cpp
- tests/clang/expected.txt
- tests/multiple/expected.txt
- tests/run.sh
- tests/swiftc/expected.txt
Instead of having a verbose mode, #37 introduced a tool for printing unit files as text ("`absolute-unit`"). With that tool, unit files can be inspected before and after remapping, and also print all unit fields, not just the path fields.
This change removes the `-verbose`/`-V` flags. The tests now use `absolute-unit` when verifying their contents.
> Remove verbose output mode

- absolute-unit.cpp
The output of `absolute-unit` is intended to be yaml (or close enough). A unit's dependencies are a list, so this adds a `-` marker to the start of each dependency block. Same for unit includes.
> Indicate list items in absolute-unit output

- index-import.cpp
When using `FileManager::getFile()`, if the path does not exist, then the unit file will contain a blank path for that field. Using `getVirtualFile()` will ensure that even invalid paths are written into the unit file. Invalid paths are useful for two reasons:
1. The file may not exist now but is expected to exist later
2. Debugging path remapping in the output of `index-import` (via `absolute-unit`)
In the second case, it's better to see an invalid path than an empty path.
The solution should be to use `getVirtualFile()` everywhere, but this function asserts if called with an empty path (which can legitimately happen[1]). The final solution is to call `getVirtualFile` in all cases except for the empty string which requires `getFile`.
1. For example, `.pcm` files have an empty …
> Write invalid remapped paths to unit files

- CMakeLists.txt
- validate-index.cpp
This adds `validate-index`, a tool to validate indexstore unit files. Currently it checks that paths exist. This is useful as a post-import step, to confirm that `index-import` produced valid paths.
Further updates may include:
1. Validating the format of `OutputFile`'s path
2. Validation of unit/record names
3. Correction of sysroot
> Add initial validate-index tool

- CMakeLists.txt
1. `clangIndexDataStore` depends on `clangIndex`, the latter doesn't need to be an explicit link dependency
2. The interface of the `clangDirectoryWatcher` target includes the `CoreServices` link options, and doesn't need to be explicit
> Small simplifications to CMakeLists.txt

- index-import.cpp
For empty paths, return `nullptr` instead of calling `FileManager::getFile()`.
This also fixes compilation against Swift 5.2.
> Update FileEntry lookup

- README.md
It was pointed out by @indragiek that the bazel example contained `/Modules/` in the path, which he wasn't seeing in his `bazel-out`. That path was specific to a project, so I've updated the README to be more generic.
This update is taken somewhat from [bazel-xcode-demo-swift-driver](https://github.com/kastiglione/bazel-xcode-demo-swift-driver/blob/9336d63e5b49792fee5cc7f317b144855b6226cb/bazel/installers/_indexstore.sh).
> Update bazel example in README

- index-import.cpp
An alternative implementation of #32.
Closes #32.
> Add option to only transfer units if they are newer

- index-import.cpp
This PR adds the capability to import output files from a compilation:
to improve performance and experiment with using a "global shared index"
while remote caching a subset for lib. The github issue has some overall
mentions of this https://github.com/bazelbuild/rules_swift/issues/561
Index while building is performant in clang and swift becauase it
conditionally writes data based on files in a global index cache reused
across all clang/swift invocations in the build. The overhead of 3-5%
performance hit in the whitepaper of "Index while building" seems hinged
on the fact it'd be using a global index cache.  With the per library
index as rules_swift implemented this feature, "Index while building"
adds a 300% increase in build times in my testing.
Longer term, can add flags to clang and …
> Import based on compilation outputs

- index-import.cpp
- tests/clang/expected.txt
- tests/multiple/expected.txt
- tests/run.sh
- tests/swiftc/expected.txt
- validate-index.cpp
This diff has a few changes that were required to get this working with
Swift 5.5:
- Tests had hardcoded architectures and SDK versions, these had to be
updated to allow for newer SDKs, and running tests on M1 machines
- The minimum OS version was hardcoded in the tests, but was not passed
to the compilers, I hardcoded the same version that was previously
used, give or take, it doesn't really matter for this case, just that
they're consistent
- The implicit conversion from llvm::StringRef to std::string was
removed in
https://github.com/llvm/llvm-project/commit/777180a32b61070a10dd330b4f038bf24e916af1,
this change now explicitly converts where required. Theoretically
there might be some performance wins by cleaning this up, but we'd
need to profile to know for sure
- Record suffixes …
> Update for Swift 5.5

- index-import.cpp
It's valid to not have records (i.e. an empty swift file), and Bazel won't create empty directories when downloading from a remote cache.
> Allow not having a records directory

- index-import.cpp
Signed-off-by: Brentley Jones <github@brentleyjones.com>
> Add temporary flag to fix rules_swift remapping

- tests/run.sh
This makes it easier to swap this out for testing older versions of
index-import against newer versions of swiftc / clang
> Extract test executables to variables

- tests/clang/expected.txt
- tests/multiple/expected.txt
- tests/run.sh
- tests/swiftc/expected.txt
Since Xcode 14 / Swift 5.7, some file paths in index units that were
previously stored relatively, are now stored absolutely. Because of this
our remaps have to change to support the new structure. Along with this,
also as of Xcode 14, `swiftc` and `clang` support remapping the paths in
indexes using `-file-prefix-map foo=bar` and `-ffile-prefix-map=foo=bar`
respectively. This can be used to remove the absolute paths entirely
from the produced index data, which then also requires a new set of
remaps to convert back to absolute for Xcode. I've mostly updated the
tests to use this remapping behavior, which everyone should use if
possible, but I left one case with updated paths to show the new
absolute path behavior.
> Update tests for compiler changes

- index-import.cpp
- tests/run.sh
The `-file-prefix-map` option allows setting the `PathRemapper` mappings the same way that `clang` does. We now also use the `PathRemapper` in `getUnitPathForOutputFile` the same as as `IndexUnitWriter`.
This change is needed to allow the use of both the `swift.use_global_index_store` and `swift.file_prefix_map` rules_swift features.
> Add `-file-prefix-map` option

- index-import.cpp
**Context** 
For a single indexstore that contains ~50k unit files, it can take ~25 minutes to just run index-import on. 
**Changes**
If single indexstore is processed, process indexstore content in parallel
**Tests**
Tested locally with a single indexstore that has 51K index unit files. 
- Before : it took 25 minutes to run index-import.
- After : 4 min 30 seconds to run index-import.
> Remap indexstore contents in parallel

- CMakeLists.txt
- index-import.cpp
Turns out that regexes were the bottleneck for large imports. This took
our import time from ~9s to ~4s.
> Replace std::regex with re2

- index-import.cpp
The index store library requires paths being written are absolute. If we
don't absolutize them then it does. Unfortunately its logic for that
computes the PWD for every single path, which can amount to ~5% of the
total time spent in index-import.
> Absolutize paths after remapping

- index-import.cpp
Absolutizing these paths resulted in failures with symlinks downstream.
Resolving those symlinks seems to work but in the case you're trying to
remap from 1 location to another not for Xcode, which rules_swift does
if you use the `swift.use_global_index_store` you actually need the
paths to still be relative in the units.
This reverts commit 431d4e5d1e75baa7316a66919160dc682ee93863.
> Revert "Absolutize paths after remapping (#91)"

- README.md
The repo's instructions were pointing to Swift 5.5, but today it makes use of [PathRemapper](https://github.com/apple/llvm-project/blob/swift/release/5.7/clang/include/clang/Basic/PathRemapper.h), which was introduced in 5.7. Closes https://github.com/MobileNativeFoundation/index-import/issues/106
> Update build instructions to require Swift 5.7

- index-import.cpp
copyfile.h is primarily a macOS API, and Swift 5.1 came out in 2019 so we can use the LLVM API directly.
> Use llvm::fs::copy_file instead of copyfile.h

- CMakeLists.txt
`-dead_strip` exists on ld64, the macOS linker, but not necessarily on other linkers.
This solves a build warning on Linux:
clang++: warning: argument unused during compilation: '-dead_strip' [-Wunused-command-line-argument]
> Only pass -dead_strip link option on macOS

- CMakeLists.txt
If the user has re2 available as a system package (e.g. re2-devel on Fedora), use that rather than downloading and compiling re2.
Abseil is only required to build re2, so don't bother downloading and building it if re2 is available.
Helps with #118.
> Use the system re2 library if available

- .github/workflows/test.yml
Add a test job that ensures that index-import can build. Do the minimum possible LLVM build rather than building all of Swift, to reduce CI time.
This is the first step for #4. I'll try to do Linux in a follow-up PR.
> Add GitHub CI exercising the build on macOS

- .github/workflows/test.yml
- RELEASING.md
- index-import.cpp
- tests/clang/expected.txt
- tests/import_only/expected.txt
- tests/multiple/expected.txt
- tests/run.sh
Fixes #120. Swift 6.1 changes the hash algorithm to BLAKE3, this change is not backwards compatible as we need to build with swiftlang/llvm-project (Swift 6.1 release). Projects that need to support all Swift 6.x (Xcode 16.0-16.2) can use both binaries (before and after this PR).
> Update for Swift 6.1 hash algorithm change

- README.md
I'm assuming the default for most developers is ARM64 at this point -- let me know if you'd like me to split the instructions into x86 & ARM.
> Update README.md for arm64

- .github/generate-notes.sh
- .github/workflows/test.yml
This hijacks the existing workflow to also do releases only when
manually dispatched with a tag. Primarily done this way to not duplicate
all logic.
> Add release logic to CI workflow
